services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: url-shortener
    container_name: url-shortener-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - url-shortener-network

  nginx:
    image: nginx:1.27-alpine
    container_name: url-shortener-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - url-shortener-network

  db:
    image: mysql:5.7
    container_name: url-shortener-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: url_shortener
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: url_shortener
    volumes:
      - dbdata:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - url-shortener-network

  redis:
    image: redis:7.4-alpine
    container_name: url-shortener-redis
    restart: unless-stopped
    networks:
      - url-shortener-network

networks:
  url-shortener-network:
    driver: bridge

volumes:
  dbdata:
    driver: local 